// Command openapi-bundle combines Mastarr's exploded OpenAPI fragments into
// the generated api/openapi.yaml document.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"gopkg.in/yaml.v3"
)

func main() {
	input := flag.String("input", "api/fragments", "fragment directory")
	output := flag.String("output", "api/openapi.yaml", "bundled OpenAPI document")
	flag.Parse()
	if err := bundle(*input, *output); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func bundle(input, output string) error {
	paths, err := fragmentPaths(input)
	if err != nil {
		return err
	}
	if len(paths) == 0 {
		return errors.New("openapi bundle: no fragments found")
	}

	document := map[string]any{}
	for _, filename := range paths {
		data, err := os.ReadFile(filename)
		if err != nil {
			return fmt.Errorf("openapi bundle: read %s: %w", filename, err)
		}
		var fragment map[string]any
		if err := yaml.Unmarshal(data, &fragment); err != nil {
			return fmt.Errorf("openapi bundle: parse %s: %w", filename, err)
		}
		if err := mergeFragment(document, fragment, filename); err != nil {
			return err
		}
	}
	if version, ok := document["openapi"].(string); !ok || version != "3.1.1" {
		return errors.New("openapi bundle: fragments must declare OpenAPI 3.1.1")
	}
	for _, required := range []string{"info", "paths", "components"} {
		if _, ok := document[required]; !ok {
			return fmt.Errorf("openapi bundle: missing top-level %q", required)
		}
	}

	data, err := yaml.Marshal(document)
	if err != nil {
		return fmt.Errorf("openapi bundle: encode: %w", err)
	}
	data = append([]byte("# Code generated by tools/internal/openapi-bundle; DO NOT EDIT.\n"), data...)
	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		return fmt.Errorf("openapi bundle: create output directory: %w", err)
	}
	if err := os.WriteFile(output, data, 0o644); err != nil {
		return fmt.Errorf("openapi bundle: write %s: %w", output, err)
	}
	return nil
}

func fragmentPaths(root string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		ext := filepath.Ext(entry.Name())
		if ext == ".yaml" || ext == ".yml" {
			paths = append(paths, path)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("openapi bundle: walk %s: %w", root, err)
	}
	sort.Strings(paths)
	return paths, nil
}

func mergeFragment(document, fragment map[string]any, filename string) error {
	for key, value := range fragment {
		switch key {
		case "paths", "components":
			incoming, ok := value.(map[string]any)
			if !ok {
				return fmt.Errorf("openapi bundle: %s %s must be a mapping", filename, key)
			}
			existing, ok := document[key].(map[string]any)
			if !ok {
				existing = map[string]any{}
				document[key] = existing
			}
			if err := mergeNamed(existing, incoming, filename, key); err != nil {
				return err
			}
		default:
			if _, exists := document[key]; exists {
				return fmt.Errorf("openapi bundle: duplicate top-level key %q in %s", key, filename)
			}
			document[key] = value
		}
	}
	return nil
}

func mergeNamed(destination, incoming map[string]any, filename, section string) error {
	for name, value := range incoming {
		if _, exists := destination[name]; exists {
			return fmt.Errorf("openapi bundle: duplicate %s key %q in %s", section, name, filename)
		}
		destination[name] = value
	}
	return nil
}
