// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ActionAttempt struct {
	ID               string         `json:"id"`
	ActionRunID      string         `json:"action_run_id"`
	AttemptNumber    int64          `json:"attempt_number"`
	Phase            string         `json:"phase"`
	State            string         `json:"state"`
	StartedAt        string         `json:"started_at"`
	FinishedAt       sql.NullString `json:"finished_at"`
	ErrorCode        sql.NullString `json:"error_code"`
	ErrorDetail      sql.NullString `json:"error_detail"`
	OutcomeCertainty string         `json:"outcome_certainty"`
	ExternalID       sql.NullString `json:"external_id"`
	EvidenceJson     string         `json:"evidence_json"`
}

type ActionEffect struct {
	ID           string         `json:"id"`
	ActionRunID  string         `json:"action_run_id"`
	AttemptID    sql.NullString `json:"attempt_id"`
	Ordinal      int64          `json:"ordinal"`
	TargetKind   string         `json:"target_kind"`
	TargetID     string         `json:"target_id"`
	EffectKind   string         `json:"effect_kind"`
	State        string         `json:"state"`
	EvidenceJson string         `json:"evidence_json"`
	ObservedAt   string         `json:"observed_at"`
}

type ActionPlan struct {
	ID              string `json:"id"`
	Kind            string `json:"kind"`
	State           string `json:"state"`
	CurrentRevision int64  `json:"current_revision"`
	CurrentDigest   string `json:"current_digest"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type ActionPlanRevision struct {
	PlanID            string         `json:"plan_id"`
	Revision          int64          `json:"revision"`
	Digest            string         `json:"digest"`
	State             string         `json:"state"`
	InputJson         string         `json:"input_json"`
	PreconditionsJson string         `json:"preconditions_json"`
	CapabilitiesJson  string         `json:"capabilities_json"`
	ManifestJson      string         `json:"manifest_json"`
	CreatedAt         string         `json:"created_at"`
	ExpiresAt         string         `json:"expires_at"`
	ReadyAt           sql.NullString `json:"ready_at"`
}

type ActionRun struct {
	ID                      string         `json:"id"`
	PlanID                  string         `json:"plan_id"`
	PlanRevision            int64          `json:"plan_revision"`
	PlanDigest              string         `json:"plan_digest"`
	State                   string         `json:"state"`
	DesiredStateJson        string         `json:"desired_state_json"`
	NextAttemptAt           sql.NullString `json:"next_attempt_at"`
	DeadlineAt              sql.NullString `json:"deadline_at"`
	CancellationRequestedAt sql.NullString `json:"cancellation_requested_at"`
	ClaimedBy               sql.NullString `json:"claimed_by"`
	LeaseUntil              sql.NullString `json:"lease_until"`
	Version                 int64          `json:"version"`
	OutcomeJson             string         `json:"outcome_json"`
	UnresolvedCount         int64          `json:"unresolved_count"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

type AuditEvent struct {
	ID           int64          `json:"id"`
	EventID      string         `json:"event_id"`
	OccurredAt   string         `json:"occurred_at"`
	Actor        string         `json:"actor"`
	Action       string         `json:"action"`
	ResourceKind string         `json:"resource_kind"`
	ResourceID   sql.NullString `json:"resource_id"`
	PlanDigest   sql.NullString `json:"plan_digest"`
	Outcome      string         `json:"outcome"`
	MetadataJson string         `json:"metadata_json"`
	Redacted     int64          `json:"redacted"`
}

type ConfigSnapshot struct {
	ID            string `json:"id"`
	Source        string `json:"source"`
	DocumentID    string `json:"document_id"`
	Revision      string `json:"revision"`
	StartupAt     string `json:"startup_at"`
	EffectiveJson string `json:"effective_json"`
	CreatedAt     string `json:"created_at"`
}

type Connection struct {
	ID               string         `json:"id"`
	Kind             string         `json:"kind"`
	Label            string         `json:"label"`
	Endpoint         string         `json:"endpoint"`
	Source           string         `json:"source"`
	SourceSnapshotID string         `json:"source_snapshot_id"`
	Revision         string         `json:"revision"`
	RetiredAt        sql.NullString `json:"retired_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type CoverageSnapshot struct {
	ID               string         `json:"id"`
	ScanID           sql.NullString `json:"scan_id"`
	SourceID         sql.NullString `json:"source_id"`
	ConnectionID     sql.NullString `json:"connection_id"`
	RootID           sql.NullString `json:"root_id"`
	Completeness     string         `json:"completeness"`
	ReasonCodesJson  string         `json:"reason_codes_json"`
	ObservedCount    int64          `json:"observed_count"`
	SnapshotRevision sql.NullString `json:"snapshot_revision"`
	StartedAt        sql.NullString `json:"started_at"`
	CompletedAt      sql.NullString `json:"completed_at"`
	ObservedAt       string         `json:"observed_at"`
	CreatedAt        string         `json:"created_at"`
	MediaIdentityID  sql.NullString `json:"media_identity_id"`
}

type Descriptor struct {
	ID                string         `json:"id"`
	DownloadID        sql.NullString `json:"download_id"`
	DescriptorType    string         `json:"descriptor_type"`
	StoragePath       string         `json:"storage_path"`
	OriginalDigest    sql.NullString `json:"original_digest"`
	CaptureSource     string         `json:"capture_source"`
	CapturedAt        string         `json:"captured_at"`
	Retention         string         `json:"retention"`
	UnavailableReason sql.NullString `json:"unavailable_reason"`
	DeletedAt         sql.NullString `json:"deleted_at"`
}

type Discovery struct {
	ID                string         `json:"id"`
	RootID            string         `json:"root_id"`
	RelativePath      string         `json:"relative_path"`
	EntryType         string         `json:"entry_type"`
	SizeBytes         int64          `json:"size_bytes"`
	Digest            sql.NullString `json:"digest"`
	FileIdentity      sql.NullString `json:"file_identity"`
	Role              sql.NullString `json:"role"`
	ObservedAt        string         `json:"observed_at"`
	FirstSeenAt       string         `json:"first_seen_at"`
	LastSeenAt        string         `json:"last_seen_at"`
	ManifestRevision  string         `json:"manifest_revision"`
	ChildManifestJson string         `json:"child_manifest_json"`
	DeletedAt         sql.NullString `json:"deleted_at"`
}

type Download struct {
	ID           string         `json:"id"`
	ConnectionID string         `json:"connection_id"`
	ExternalID   string         `json:"external_id"`
	Protocol     string         `json:"protocol"`
	Name         sql.NullString `json:"name"`
	ContentHash  sql.NullString `json:"content_hash"`
	NzbID        sql.NullString `json:"nzb_id"`
	State        string         `json:"state"`
	CompletedAt  sql.NullString `json:"completed_at"`
	SeedingState sql.NullString `json:"seeding_state"`
	PayloadJson  string         `json:"payload_json"`
	HistoryJson  string         `json:"history_json"`
	FirstSeenAt  string         `json:"first_seen_at"`
	LastSeenAt   string         `json:"last_seen_at"`
}

type EarlyPurgePlanTarget struct {
	PlanID            string `json:"plan_id"`
	Revision          int64  `json:"revision"`
	PlanDigest        string `json:"plan_digest"`
	IntentKind        string `json:"intent_kind"`
	TrashEntryID      string `json:"trash_entry_id"`
	TrashEntryVersion int64  `json:"trash_entry_version"`
	ManifestJson      string `json:"manifest_json"`
	CreatedAt         string `json:"created_at"`
}

type EncryptedCredential struct {
	ConnectionID    string `json:"connection_id"`
	Name            string `json:"name"`
	EnvelopeVersion int64  `json:"envelope_version"`
	Nonce           []byte `json:"nonce"`
	Ciphertext      []byte `json:"ciphertext"`
	KeyFingerprint  string `json:"key_fingerprint"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type ExternalRecord struct {
	ID              string         `json:"id"`
	ConnectionID    string         `json:"connection_id"`
	MediaIdentityID sql.NullString `json:"media_identity_id"`
	RecordKind      string         `json:"record_kind"`
	ExternalID      string         `json:"external_id"`
	Title           sql.NullString `json:"title"`
	PayloadJson     string         `json:"payload_json"`
	ObservedAt      string         `json:"observed_at"`
	FirstSeenAt     string         `json:"first_seen_at"`
	LastSeenAt      string         `json:"last_seen_at"`
}

type FileObservation struct {
	ID                string         `json:"id"`
	DiscoveryID       string         `json:"discovery_id"`
	RootID            string         `json:"root_id"`
	RelativePath      string         `json:"relative_path"`
	EntryType         string         `json:"entry_type"`
	SizeBytes         int64          `json:"size_bytes"`
	Digest            sql.NullString `json:"digest"`
	FileIdentity      sql.NullString `json:"file_identity"`
	Role              sql.NullString `json:"role"`
	ObservedAt        string         `json:"observed_at"`
	ManifestRevision  string         `json:"manifest_revision"`
	ChildManifestJson string         `json:"child_manifest_json"`
	FirstSeenAt       string         `json:"first_seen_at"`
	LastSeenAt        string         `json:"last_seen_at"`
	DeletedAt         sql.NullString `json:"deleted_at"`
}

type IdempotencyRecord struct {
	Scope          string         `json:"scope"`
	IdempotencyKey string         `json:"idempotency_key"`
	RequestDigest  string         `json:"request_digest"`
	StatusCode     int64          `json:"status_code"`
	ResourceKind   string         `json:"resource_kind"`
	ResourceID     string         `json:"resource_id"`
	ResponseJson   string         `json:"response_json"`
	CreatedAt      string         `json:"created_at"`
	ExpiresAt      sql.NullString `json:"expires_at"`
}

type JanitorRecord struct {
	ID                       string         `json:"id"`
	TrashEntryID             string         `json:"trash_entry_id"`
	Operation                string         `json:"operation"`
	State                    string         `json:"state"`
	NextAttemptAt            sql.NullString `json:"next_attempt_at"`
	ClaimedBy                sql.NullString `json:"claimed_by"`
	LeaseUntil               sql.NullString `json:"lease_until"`
	OutcomeJson              string         `json:"outcome_json"`
	CreatedAt                string         `json:"created_at"`
	UpdatedAt                string         `json:"updated_at"`
	Version                  int64          `json:"version"`
	ApprovalPlanID           sql.NullString `json:"approval_plan_id"`
	ApprovalPlanRevision     sql.NullInt64  `json:"approval_plan_revision"`
	ApprovalPlanDigest       sql.NullString `json:"approval_plan_digest"`
	ApprovalDecisionID       sql.NullString `json:"approval_decision_id"`
	ApprovalActionRunID      sql.NullString `json:"approval_action_run_id"`
	ApprovedEntryVersion     sql.NullInt64  `json:"approved_entry_version"`
	ApprovalActionRunVersion sql.NullInt64  `json:"approval_action_run_version"`
}

type MediaIdentity struct {
	ID                string         `json:"id"`
	Kind              string         `json:"kind"`
	ProviderNamespace sql.NullString `json:"provider_namespace"`
	ProviderID        sql.NullString `json:"provider_id"`
	Title             string         `json:"title"`
	Year              sql.NullInt64  `json:"year"`
	CanonicalKey      string         `json:"canonical_key"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type PathMapping struct {
	ID                string         `json:"id"`
	ConnectionID      string         `json:"connection_id"`
	RootID            string         `json:"root_id"`
	SourcePrefix      string         `json:"source_prefix"`
	DestinationPrefix string         `json:"destination_prefix"`
	Source            string         `json:"source"`
	SourceSnapshotID  string         `json:"source_snapshot_id"`
	Revision          string         `json:"revision"`
	RetiredAt         sql.NullString `json:"retired_at"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type PlanManifest struct {
	PlanID       string         `json:"plan_id"`
	Revision     int64          `json:"revision"`
	Ordinal      int64          `json:"ordinal"`
	RootID       string         `json:"root_id"`
	RelativePath string         `json:"relative_path"`
	EntryType    string         `json:"entry_type"`
	SizeBytes    int64          `json:"size_bytes"`
	Digest       sql.NullString `json:"digest"`
	FileIdentity sql.NullString `json:"file_identity"`
	Role         sql.NullString `json:"role"`
	ManifestJson string         `json:"manifest_json"`
}

type ProvenanceLink struct {
	ID           string `json:"id"`
	DiscoveryID  string `json:"discovery_id"`
	DownloadID   string `json:"download_id"`
	EvidenceJson string `json:"evidence_json"`
	ObservedAt   string `json:"observed_at"`
	FirstSeenAt  string `json:"first_seen_at"`
	LastSeenAt   string `json:"last_seen_at"`
}

type ReviewDecision struct {
	ID               string         `json:"id"`
	PlanID           string         `json:"plan_id"`
	PlanRevision     int64          `json:"plan_revision"`
	PlanDigest       string         `json:"plan_digest"`
	Decision         string         `json:"decision"`
	Actor            string         `json:"actor"`
	CallerLabel      sql.NullString `json:"caller_label"`
	Reason           sql.NullString `json:"reason"`
	IdempotencyScope string         `json:"idempotency_scope"`
	IdempotencyKey   string         `json:"idempotency_key"`
	CreatedAt        string         `json:"created_at"`
}

type Scan struct {
	ID             string         `json:"id"`
	ScopeKind      string         `json:"scope_kind"`
	ScopeID        string         `json:"scope_id"`
	State          string         `json:"state"`
	Completeness   string         `json:"completeness"`
	Cursor         sql.NullString `json:"cursor"`
	ObservedCount  int64          `json:"observed_count"`
	StartedAt      sql.NullString `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	ConfigRevision sql.NullString `json:"config_revision"`
	ErrorCode      sql.NullString `json:"error_code"`
	ErrorDetail    sql.NullString `json:"error_detail"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type StorageRoot struct {
	ID                   string         `json:"id"`
	Label                string         `json:"label"`
	Purpose              string         `json:"purpose"`
	Path                 string         `json:"path"`
	Source               string         `json:"source"`
	SourceSnapshotID     string         `json:"source_snapshot_id"`
	Revision             string         `json:"revision"`
	ReadOnly             int64          `json:"read_only"`
	WatchEnabled         int64          `json:"watch_enabled"`
	WatchIntervalSeconds int64          `json:"watch_interval_seconds"`
	CapabilitiesJson     string         `json:"capabilities_json"`
	RetiredAt            sql.NullString `json:"retired_at"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

type TrackingObservation struct {
	ID                    string         `json:"id"`
	ExternalRecordID      sql.NullString `json:"external_record_id"`
	MediaIdentityID       sql.NullString `json:"media_identity_id"`
	ConnectionID          string         `json:"connection_id"`
	RootID                sql.NullString `json:"root_id"`
	Dimension             string         `json:"dimension"`
	Status                string         `json:"status"`
	EvidenceJson          string         `json:"evidence_json"`
	CoverageID            sql.NullString `json:"coverage_id"`
	CoverageMaxAgeSeconds sql.NullInt64  `json:"coverage_max_age_seconds"`
	ObservedAt            string         `json:"observed_at"`
	RegisteredAt          sql.NullString `json:"registered_at"`
	ImportedAt            sql.NullString `json:"imported_at"`
}

type TrackingObservationQuarantine struct {
	ID                       string         `json:"id"`
	OriginalObservationID    string         `json:"original_observation_id"`
	Reason                   string         `json:"reason"`
	OriginalExternalRecordID sql.NullString `json:"original_external_record_id"`
	OriginalMediaIdentityID  sql.NullString `json:"original_media_identity_id"`
	OriginalConnectionID     sql.NullString `json:"original_connection_id"`
	OriginalRootID           sql.NullString `json:"original_root_id"`
	Dimension                string         `json:"dimension"`
	OriginalStatus           string         `json:"original_status"`
	NormalizedStatus         string         `json:"normalized_status"`
	OriginalEvidenceJson     string         `json:"original_evidence_json"`
	CoverageID               sql.NullString `json:"coverage_id"`
	CoverageMaxAgeSeconds    sql.NullInt64  `json:"coverage_max_age_seconds"`
	ObservedAt               string         `json:"observed_at"`
	RegisteredAt             sql.NullString `json:"registered_at"`
	ImportedAt               sql.NullString `json:"imported_at"`
	QuarantinedAt            string         `json:"quarantined_at"`
	SourceSchemaVersion      int64          `json:"source_schema_version"`
}

type TrashEntry struct {
	ID                  string         `json:"id"`
	RootID              string         `json:"root_id"`
	State               string         `json:"state"`
	OriginalPrefix      string         `json:"original_prefix"`
	TrashPrefix         string         `json:"trash_prefix"`
	ManifestJson        string         `json:"manifest_json"`
	RetentionSeconds    int64          `json:"retention_seconds"`
	TrashedAt           sql.NullString `json:"trashed_at"`
	ExpiresAt           string         `json:"expires_at"`
	HoldReason          sql.NullString `json:"hold_reason"`
	ClientStateJson     string         `json:"client_state_json"`
	PurgeClaimedAt      sql.NullString `json:"purge_claimed_at"`
	RestoreRequestedAt  sql.NullString `json:"restore_requested_at"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	ActiveOperation     sql.NullString `json:"active_operation"`
	OperationClaimedBy  sql.NullString `json:"operation_claimed_by"`
	OperationLeaseUntil sql.NullString `json:"operation_lease_until"`
	Version             int64          `json:"version"`
}

type TrashItem struct {
	ID                   string         `json:"id"`
	EntryID              string         `json:"entry_id"`
	RootID               string         `json:"root_id"`
	OriginalRelativePath string         `json:"original_relative_path"`
	TrashRelativePath    string         `json:"trash_relative_path"`
	EntryType            string         `json:"entry_type"`
	SizeBytes            int64          `json:"size_bytes"`
	Digest               sql.NullString `json:"digest"`
	FileIdentity         sql.NullString `json:"file_identity"`
	ClientConnectionID   sql.NullString `json:"client_connection_id"`
	ClientExternalID     sql.NullString `json:"client_external_id"`
	State                string         `json:"state"`
	TrashedAt            sql.NullString `json:"trashed_at"`
	RestoredAt           sql.NullString `json:"restored_at"`
	PurgedAt             sql.NullString `json:"purged_at"`
}

type WorkflowRun struct {
	ID                      string         `json:"id"`
	RecipeKind              string         `json:"recipe_kind"`
	RecipeVersion           int64          `json:"recipe_version"`
	State                   string         `json:"state"`
	DeadlineAt              sql.NullString `json:"deadline_at"`
	CancellationRequestedAt sql.NullString `json:"cancellation_requested_at"`
	CurrentStep             int64          `json:"current_step"`
	RecipeJson              string         `json:"recipe_json"`
	OutcomeJson             string         `json:"outcome_json"`
	CreatedAt               string         `json:"created_at"`
	UpdatedAt               string         `json:"updated_at"`
}

type WorkflowStep struct {
	ID                 string         `json:"id"`
	WorkflowID         string         `json:"workflow_id"`
	StepIndex          int64          `json:"step_index"`
	Kind               string         `json:"kind"`
	State              string         `json:"state"`
	ActionPlanID       sql.NullString `json:"action_plan_id"`
	ActionPlanRevision sql.NullInt64  `json:"action_plan_revision"`
	GateKind           sql.NullString `json:"gate_kind"`
	OutcomeJson        string         `json:"outcome_json"`
	CreatedAt          string         `json:"created_at"`
	UpdatedAt          string         `json:"updated_at"`
}
