// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimActionRun(ctx context.Context, arg *ClaimActionRunParams) (*ActionRun, error)
	// Binds an explicit approval and the exact trash-entry version in the same
	// claim statement. The migration trigger validates the immutable plan,
	// decision and action-run identities before it changes the shared entry.
	ClaimApprovedEarlyPurge(ctx context.Context, arg *ClaimApprovedEarlyPurgeParams) (*JanitorRecord, error)
	// Reacquires a janitor/trash lease for read-only reconciliation after startup
	// recovery. The associated action run remains reconciling but is fenced with
	// the same worker lease by the migration trigger; no external mutation is
	// dispatched by this CAS. The trash generation follows the current janitor
	// generation, rather than a fixed offset from the approval-time version.
	ClaimApprovedEarlyPurgeReconciliation(ctx context.Context, arg *ClaimApprovedEarlyPurgeReconciliationParams) (*JanitorRecord, error)
	ClaimJanitorRecord(ctx context.Context, arg *ClaimJanitorRecordParams) (*JanitorRecord, error)
	CreateActionAttempt(ctx context.Context, arg *CreateActionAttemptParams) (*ActionAttempt, error)
	CreateActionEffect(ctx context.Context, arg *CreateActionEffectParams) (*ActionEffect, error)
	// Immutable plans, exact manifests, approvals and durable execution records.
	CreateActionPlan(ctx context.Context, arg *CreateActionPlanParams) (*ActionPlan, error)
	CreateActionPlanRevision(ctx context.Context, arg *CreateActionPlanRevisionParams) (*ActionPlanRevision, error)
	CreateActionRun(ctx context.Context, arg *CreateActionRunParams) (*ActionRun, error)
	CreateAuditEvent(ctx context.Context, arg *CreateAuditEventParams) (*AuditEvent, error)
	// Configuration snapshots and source-owned resources.
	CreateConfigSnapshot(ctx context.Context, arg *CreateConfigSnapshotParams) (*ConfigSnapshot, error)
	CreateConnection(ctx context.Context, arg *CreateConnectionParams) (*Connection, error)
	CreateCoverageSnapshot(ctx context.Context, arg *CreateCoverageSnapshotParams) (*CoverageSnapshot, error)
	CreateDescriptor(ctx context.Context, arg *CreateDescriptorParams) (*Descriptor, error)
	CreateDiscovery(ctx context.Context, arg *CreateDiscoveryParams) (*Discovery, error)
	// Download provenance and descriptors.
	CreateDownload(ctx context.Context, arg *CreateDownloadParams) (*Download, error)
	CreateEarlyPurgePlanTarget(ctx context.Context, arg *CreateEarlyPurgePlanTargetParams) (*EarlyPurgePlanTarget, error)
	CreateExternalRecord(ctx context.Context, arg *CreateExternalRecordParams) (*ExternalRecord, error)
	CreateFileObservation(ctx context.Context, arg *CreateFileObservationParams) (*FileObservation, error)
	// Idempotency and audit are intentionally append-only.
	CreateIdempotencyRecord(ctx context.Context, arg *CreateIdempotencyRecordParams) (*IdempotencyRecord, error)
	CreateJanitorRecord(ctx context.Context, arg *CreateJanitorRecordParams) (*JanitorRecord, error)
	// Media identities and all per-instance upstream records.
	CreateMediaIdentity(ctx context.Context, arg *CreateMediaIdentityParams) (*MediaIdentity, error)
	CreatePathMapping(ctx context.Context, arg *CreatePathMappingParams) (*PathMapping, error)
	CreatePlanManifest(ctx context.Context, arg *CreatePlanManifestParams) (*PlanManifest, error)
	CreateProvenanceLink(ctx context.Context, arg *CreateProvenanceLinkParams) (*ProvenanceLink, error)
	CreateReviewDecision(ctx context.Context, arg *CreateReviewDecisionParams) (*ReviewDecision, error)
	// Discovery and coverage observations.
	CreateScan(ctx context.Context, arg *CreateScanParams) (*Scan, error)
	CreateStorageRoot(ctx context.Context, arg *CreateStorageRootParams) (*StorageRoot, error)
	CreateTrackingObservation(ctx context.Context, arg *CreateTrackingObservationParams) (*TrackingObservation, error)
	// Trash and janitor journal.
	CreateTrashEntry(ctx context.Context, arg *CreateTrashEntryParams) (*TrashEntry, error)
	CreateTrashItem(ctx context.Context, arg *CreateTrashItemParams) (*TrashItem, error)
	CreateWorkflowRun(ctx context.Context, arg *CreateWorkflowRunParams) (*WorkflowRun, error)
	CreateWorkflowStep(ctx context.Context, arg *CreateWorkflowStepParams) (*WorkflowStep, error)
	FinalizeCancelledActionAttempts(ctx context.Context, now sql.NullString) ([]*ActionAttempt, error)
	// Cancellation is terminal for undispatched queue work. A running or
	// reconciling row remains visible until its possible effect is reconciled.
	FinalizeCancelledActionRuns(ctx context.Context, now string) ([]*ActionRun, error)
	FinalizeDeadlineActionAttempts(ctx context.Context, now sql.NullString) ([]*ActionAttempt, error)
	FinalizeDeadlineActionRuns(ctx context.Context, now string) ([]*ActionRun, error)
	GetActionPlan(ctx context.Context, id string) (*ActionPlan, error)
	GetActionPlanRevision(ctx context.Context, arg *GetActionPlanRevisionParams) (*ActionPlanRevision, error)
	GetActionPlanRevisionByDigest(ctx context.Context, arg *GetActionPlanRevisionByDigestParams) (*ActionPlanRevision, error)
	GetActionRun(ctx context.Context, id string) (*ActionRun, error)
	GetConfigSnapshot(ctx context.Context, id string) (*ConfigSnapshot, error)
	GetConnection(ctx context.Context, id string) (*Connection, error)
	GetCoverageSnapshot(ctx context.Context, id string) (*CoverageSnapshot, error)
	GetDescriptor(ctx context.Context, id string) (*Descriptor, error)
	GetDiscovery(ctx context.Context, id string) (*Discovery, error)
	GetDownload(ctx context.Context, id string) (*Download, error)
	GetDownloadByExternalID(ctx context.Context, arg *GetDownloadByExternalIDParams) (*Download, error)
	GetEarlyPurgePlanTarget(ctx context.Context, arg *GetEarlyPurgePlanTargetParams) (*EarlyPurgePlanTarget, error)
	GetEncryptedCredential(ctx context.Context, arg *GetEncryptedCredentialParams) (*EncryptedCredential, error)
	GetIdempotencyRecord(ctx context.Context, arg *GetIdempotencyRecordParams) (*IdempotencyRecord, error)
	GetJanitorRecord(ctx context.Context, arg *GetJanitorRecordParams) (*JanitorRecord, error)
	GetMediaIdentity(ctx context.Context, id string) (*MediaIdentity, error)
	GetPathMapping(ctx context.Context, id string) (*PathMapping, error)
	GetReviewDecision(ctx context.Context, id string) (*ReviewDecision, error)
	GetScan(ctx context.Context, id string) (*Scan, error)
	GetStorageRoot(ctx context.Context, id string) (*StorageRoot, error)
	GetTrashEntry(ctx context.Context, id string) (*TrashEntry, error)
	GetWorkflowRun(ctx context.Context, id string) (*WorkflowRun, error)
	ListActionAttempts(ctx context.Context, actionRunID string) ([]*ActionAttempt, error)
	ListActionEffects(ctx context.Context, actionRunID string) ([]*ActionEffect, error)
	ListActionPlanRevisions(ctx context.Context, planID string) ([]*ActionPlanRevision, error)
	ListAuditEvents(ctx context.Context, arg *ListAuditEventsParams) ([]*AuditEvent, error)
	ListConfigSnapshots(ctx context.Context, arg *ListConfigSnapshotsParams) ([]*ConfigSnapshot, error)
	ListConnections(ctx context.Context, arg *ListConnectionsParams) ([]*Connection, error)
	ListCoverageSnapshots(ctx context.Context, arg *ListCoverageSnapshotsParams) ([]*CoverageSnapshot, error)
	ListDiscoveries(ctx context.Context, arg *ListDiscoveriesParams) ([]*Discovery, error)
	ListDownloads(ctx context.Context, arg *ListDownloadsParams) ([]*Download, error)
	ListDueActionRuns(ctx context.Context, arg *ListDueActionRunsParams) ([]*ActionRun, error)
	ListDueJanitorRecords(ctx context.Context, arg *ListDueJanitorRecordsParams) ([]*JanitorRecord, error)
	ListDueTrashEntries(ctx context.Context, arg *ListDueTrashEntriesParams) ([]*TrashEntry, error)
	ListEarlyPurgePlanTargets(ctx context.Context) ([]*EarlyPurgePlanTarget, error)
	ListEncryptedCredentials(ctx context.Context, connectionID string) ([]*ListEncryptedCredentialsRow, error)
	ListExternalRecords(ctx context.Context, arg *ListExternalRecordsParams) ([]*ExternalRecord, error)
	ListFileObservations(ctx context.Context, discoveryID string) ([]*FileObservation, error)
	ListPathMappings(ctx context.Context, arg *ListPathMappingsParams) ([]*PathMapping, error)
	ListPlanManifests(ctx context.Context, arg *ListPlanManifestsParams) ([]*PlanManifest, error)
	ListProvenanceForDiscovery(ctx context.Context, discoveryID string) ([]*ListProvenanceForDiscoveryRow, error)
	ListStorageRoots(ctx context.Context, arg *ListStorageRootsParams) ([]*StorageRoot, error)
	// Quarantined compatibility rows are durable operator evidence, but are kept
	// separate from active tracking observations and must never satisfy a tracking
	// lookup or absence predicate.
	ListTrackingObservationQuarantine(ctx context.Context) ([]*TrackingObservationQuarantine, error)
	ListTrackingObservations(ctx context.Context, arg *ListTrackingObservationsParams) ([]*TrackingObservation, error)
	ListTrashItems(ctx context.Context, entryID string) ([]*TrashItem, error)
	ListWorkflowSteps(ctx context.Context, workflowID string) ([]*WorkflowStep, error)
	PutEncryptedCredential(ctx context.Context, arg *PutEncryptedCredentialParams) (*EncryptedCredential, error)
	// A live worker can use the same transition when a lease expires between
	// scheduler ticks; callers must reconcile before any new dispatch.
	RecoverExpiredActionRuns(ctx context.Context, now sql.NullString) ([]*ActionRun, error)
	RecoverExpiredJanitorRecords(ctx context.Context, now string) ([]*JanitorRecord, error)
	RecoverRunningActionAttempts(ctx context.Context) ([]*ActionAttempt, error)
	// Startup recovery turns every previously claimed dispatch into read-only
	// reconciliation. No external call is retried from a running row blindly.
	RecoverRunningActionRuns(ctx context.Context, now sql.NullString) ([]*ActionRun, error)
	// The trigger on janitor_records releases the worker lease on the shared
	// trash entry while preserving its active operation for safe reconciliation.
	RecoverRunningJanitorRecords(ctx context.Context, now string) ([]*JanitorRecord, error)
	RequestActionCancellation(ctx context.Context, arg *RequestActionCancellationParams) (*ActionRun, error)
	RetireConnection(ctx context.Context, arg *RetireConnectionParams) (*Connection, error)
	RetirePathMapping(ctx context.Context, arg *RetirePathMappingParams) (*PathMapping, error)
	RetireStorageRoot(ctx context.Context, arg *RetireStorageRootParams) (*StorageRoot, error)
	UpdateActionAttempt(ctx context.Context, arg *UpdateActionAttemptParams) (*ActionAttempt, error)
	UpdateActionEffect(ctx context.Context, arg *UpdateActionEffectParams) (*ActionEffect, error)
	UpdateActionPlanState(ctx context.Context, arg *UpdateActionPlanStateParams) (*ActionPlan, error)
	UpdateActionRunOutcome(ctx context.Context, arg *UpdateActionRunOutcomeParams) (*ActionRun, error)
	UpdateJanitorRecord(ctx context.Context, arg *UpdateJanitorRecordParams) (*JanitorRecord, error)
	UpdateScan(ctx context.Context, arg *UpdateScanParams) (*Scan, error)
	UpdateTrashEntryState(ctx context.Context, arg *UpdateTrashEntryStateParams) (*TrashEntry, error)
	UpdateWorkflowRunState(ctx context.Context, arg *UpdateWorkflowRunStateParams) (*WorkflowRun, error)
}

var _ Querier = (*Queries)(nil)
