// Code generated by tools/internal/nzbgetgen; DO NOT EDIT.

package nzbget

import "context"

// Invoker is implemented by the handwritten transport. Generated methods
// only describe the typed wire call and never perform HTTP themselves.
type Invoker interface {
	Invoke(context.Context, string, []any, any) error
}

// Methods exposes the four read-only positional NZBGet methods.
type Methods struct {
	invoker Invoker
}

// NewMethods binds generated wrappers to a transport.
func NewMethods(invoker Invoker) Methods { return Methods{invoker: invoker} }

const MethodVersion = "version"

const MethodListGroups = "listgroups"

const MethodListFiles = "listfiles"

const MethodHistory = "history"

// FileRecord is the generated NZBGet wire representation of FileRecord.
type FileRecord struct {
	ID                int64   `json:"ID"`
	NZBID             int64   `json:"NZBID"`
	NZBFilename       string  `json:"NZBFilename"`
	NZBName           string  `json:"NZBName"`
	NZBNicename       *string `json:"NZBNicename"`
	Subject           *string `json:"Subject"`
	Filename          *string `json:"Filename"`
	FilenameConfirmed *bool   `json:"FilenameConfirmed"`
	DestDir           *string `json:"DestDir"`
	FileSizeLo        uint32  `json:"FileSizeLo"`
	FileSizeHi        uint32  `json:"FileSizeHi"`
	RemainingSizeLo   uint32  `json:"RemainingSizeLo"`
	RemainingSizeHi   uint32  `json:"RemainingSizeHi"`
	Paused            *bool   `json:"Paused"`
	PostTime          *int64  `json:"PostTime"`
	Category          *string `json:"Category"`
	Priority          *int64  `json:"Priority"`
	ActiveDownloads   *int64  `json:"ActiveDownloads"`
	Progress          *int64  `json:"Progress"`
}

// GroupRecord is the generated NZBGet wire representation of GroupRecord.
type GroupRecord struct {
	NZBID              int64            `json:"NZBID"`
	ID                 *int64           `json:"ID"`
	FirstID            *int64           `json:"FirstID"`
	LastID             *int64           `json:"LastID"`
	NZBFilename        string           `json:"NZBFilename"`
	NZBName            string           `json:"NZBName"`
	NZBNicename        *string          `json:"NZBNicename"`
	Kind               string           `json:"Kind"`
	URL                *string          `json:"URL"`
	DestDir            string           `json:"DestDir"`
	FinalDir           *string          `json:"FinalDir"`
	Category           string           `json:"Category"`
	FileSizeLo         uint32           `json:"FileSizeLo"`
	FileSizeHi         uint32           `json:"FileSizeHi"`
	FileSizeMB         int64            `json:"FileSizeMB"`
	RemainingSizeLo    uint32           `json:"RemainingSizeLo"`
	RemainingSizeHi    uint32           `json:"RemainingSizeHi"`
	RemainingSizeMB    int64            `json:"RemainingSizeMB"`
	PausedSizeLo       uint32           `json:"PausedSizeLo"`
	PausedSizeHi       uint32           `json:"PausedSizeHi"`
	PausedSizeMB       int64            `json:"PausedSizeMB"`
	FileCount          int64            `json:"FileCount"`
	RemainingFileCount int64            `json:"RemainingFileCount"`
	RemainingParCount  int64            `json:"RemainingParCount"`
	MinPostTime        *int64           `json:"MinPostTime"`
	MaxPostTime        *int64           `json:"MaxPostTime"`
	MinPriority        *int64           `json:"MinPriority"`
	MaxPriority        *int64           `json:"MaxPriority"`
	ActiveDownloads    int64            `json:"ActiveDownloads"`
	Status             string           `json:"Status"`
	TotalArticles      int64            `json:"TotalArticles"`
	SuccessArticles    int64            `json:"SuccessArticles"`
	FailedArticles     int64            `json:"FailedArticles"`
	Health             int64            `json:"Health"`
	CriticalHealth     int64            `json:"CriticalHealth"`
	DownloadedSizeLo   *uint32          `json:"DownloadedSizeLo"`
	DownloadedSizeHi   *uint32          `json:"DownloadedSizeHi"`
	DownloadedSizeMB   *int64           `json:"DownloadedSizeMB"`
	DownloadTimeSec    *int64           `json:"DownloadTimeSec"`
	MessageCount       *int64           `json:"MessageCount"`
	DupeKey            *string          `json:"DupeKey"`
	DupeScore          *int64           `json:"DupeScore"`
	DupeMode           *string          `json:"DupeMode"`
	Parameters         []Parameter      `json:"Parameters"`
	ServerStats        []ServerStat     `json:"ServerStats"`
	ParStatus          *string          `json:"ParStatus"`
	UnpackStatus       *string          `json:"UnpackStatus"`
	ExParStatus        *string          `json:"ExParStatus"`
	MoveStatus         *string          `json:"MoveStatus"`
	ScriptStatus       *string          `json:"ScriptStatus"`
	DeleteStatus       *string          `json:"DeleteStatus"`
	UrlStatus          *string          `json:"UrlStatus"`
	MarkStatus         *string          `json:"MarkStatus"`
	ScriptStatuses     []ScriptStatus   `json:"ScriptStatuses"`
	PostInfoText       *string          `json:"PostInfoText"`
	PostStageProgress  *int64           `json:"PostStageProgress"`
	PostTotalTimeSec   *int64           `json:"PostTotalTimeSec"`
	PostStageTimeSec   *int64           `json:"PostStageTimeSec"`
	ParTimeSec         *int64           `json:"ParTimeSec"`
	RepairTimeSec      *int64           `json:"RepairTimeSec"`
	UnpackTimeSec      *int64           `json:"UnpackTimeSec"`
	Deleted            *bool            `json:"Deleted"`
	Log                []map[string]any `json:"Log"`
}

// HistoryRecord is the generated NZBGet wire representation of HistoryRecord.
type HistoryRecord struct {
	NZBID              int64            `json:"NZBID"`
	ID                 *int64           `json:"ID"`
	Kind               string           `json:"Kind"`
	NZBFilename        string           `json:"NZBFilename"`
	Name               string           `json:"Name"`
	NZBName            *string          `json:"NZBName"`
	NZBNicename        *string          `json:"NZBNicename"`
	URL                *string          `json:"URL"`
	RetryData          *bool            `json:"RetryData"`
	HistoryTime        *int64           `json:"HistoryTime"`
	DestDir            string           `json:"DestDir"`
	FinalDir           *string          `json:"FinalDir"`
	Category           string           `json:"Category"`
	FileSizeLo         uint32           `json:"FileSizeLo"`
	FileSizeHi         uint32           `json:"FileSizeHi"`
	FileSizeMB         *int64           `json:"FileSizeMB"`
	FileCount          int64            `json:"FileCount"`
	RemainingFileCount int64            `json:"RemainingFileCount"`
	MinPostTime        *int64           `json:"MinPostTime"`
	MaxPostTime        *int64           `json:"MaxPostTime"`
	TotalArticles      int64            `json:"TotalArticles"`
	SuccessArticles    int64            `json:"SuccessArticles"`
	FailedArticles     int64            `json:"FailedArticles"`
	Health             int64            `json:"Health"`
	CriticalHealth     int64            `json:"CriticalHealth"`
	Deleted            *bool            `json:"Deleted"`
	DownloadedSizeLo   *uint32          `json:"DownloadedSizeLo"`
	DownloadedSizeHi   *uint32          `json:"DownloadedSizeHi"`
	DownloadedSizeMB   *int64           `json:"DownloadedSizeMB"`
	DownloadTimeSec    *int64           `json:"DownloadTimeSec"`
	PostTotalTimeSec   *int64           `json:"PostTotalTimeSec"`
	ParTimeSec         *int64           `json:"ParTimeSec"`
	RepairTimeSec      *int64           `json:"RepairTimeSec"`
	UnpackTimeSec      *int64           `json:"UnpackTimeSec"`
	MessageCount       *int64           `json:"MessageCount"`
	DupeKey            *string          `json:"DupeKey"`
	DupeScore          *int64           `json:"DupeScore"`
	DupeMode           *string          `json:"DupeMode"`
	Status             string           `json:"Status"`
	ParStatus          *string          `json:"ParStatus"`
	ExParStatus        *string          `json:"ExParStatus"`
	UnpackStatus       *string          `json:"UnpackStatus"`
	UrlStatus          *string          `json:"UrlStatus"`
	ScriptStatus       *string          `json:"ScriptStatus"`
	ScriptStatuses     []ScriptStatus   `json:"ScriptStatuses"`
	MoveStatus         *string          `json:"MoveStatus"`
	DeleteStatus       *string          `json:"DeleteStatus"`
	MarkStatus         *string          `json:"MarkStatus"`
	ExtraParBlocks     *int64           `json:"ExtraParBlocks"`
	Parameters         []Parameter      `json:"Parameters"`
	ServerStats        []ServerStat     `json:"ServerStats"`
	Log                []map[string]any `json:"Log"`
}

// Parameter is the generated NZBGet wire representation of Parameter.
type Parameter struct {
	Name  string  `json:"Name"`
	Value *string `json:"Value"`
}

// ScriptStatus is the generated NZBGet wire representation of ScriptStatus.
type ScriptStatus struct {
	Name   string `json:"Name"`
	Status string `json:"Status"`
}

// ServerStat is the generated NZBGet wire representation of ServerStat.
type ServerStat struct {
	ServerID        int64 `json:"ServerID"`
	SuccessArticles int64 `json:"SuccessArticles"`
	FailedArticles  int64 `json:"FailedArticles"`
}

// VersionResult is the generated NZBGet wire representation of VersionResult.
type VersionResult string

// VersionRequest contains the exact positional arguments for version.
type VersionRequest struct {
}

// Params returns arguments in NZBGet's required by-position order.
func (request VersionRequest) Params() []any {
	return []any{}
}

// Version invokes version through the bound transport.
func (methods Methods) Version(ctx context.Context, request VersionRequest) (VersionResult, error) {
	var result VersionResult
	if err := methods.invoker.Invoke(ctx, MethodVersion, request.Params(), &result); err != nil {
		return result, err
	}
	return result, nil
}

// ListGroupsRequest contains the exact positional arguments for listgroups.
type ListGroupsRequest struct {
	NumberOfLogEntries int64
}

// Params returns arguments in NZBGet's required by-position order.
func (request ListGroupsRequest) Params() []any {
	return []any{request.NumberOfLogEntries}
}

// ListGroups invokes listgroups through the bound transport.
func (methods Methods) ListGroups(ctx context.Context, request ListGroupsRequest) ([]GroupRecord, error) {
	var result []GroupRecord
	if err := methods.invoker.Invoke(ctx, MethodListGroups, request.Params(), &result); err != nil {
		return result, err
	}
	return result, nil
}

// ListFilesRequest contains the exact positional arguments for listfiles.
type ListFilesRequest struct {
	IDFrom int64
	IDTo   int64
	NZBID  int64
}

// Params returns arguments in NZBGet's required by-position order.
func (request ListFilesRequest) Params() []any {
	return []any{request.IDFrom, request.IDTo, request.NZBID}
}

// ListFiles invokes listfiles through the bound transport.
func (methods Methods) ListFiles(ctx context.Context, request ListFilesRequest) ([]FileRecord, error) {
	var result []FileRecord
	if err := methods.invoker.Invoke(ctx, MethodListFiles, request.Params(), &result); err != nil {
		return result, err
	}
	return result, nil
}

// HistoryRequest contains the exact positional arguments for history.
type HistoryRequest struct {
	Hidden bool
}

// Params returns arguments in NZBGet's required by-position order.
func (request HistoryRequest) Params() []any {
	return []any{request.Hidden}
}

// History invokes history through the bound transport.
func (methods Methods) History(ctx context.Context, request HistoryRequest) ([]HistoryRecord, error) {
	var result []HistoryRecord
	if err := methods.invoker.Invoke(ctx, MethodHistory, request.Params(), &result); err != nil {
		return result, err
	}
	return result, nil
}
